<a href="https://colab.research.google.com/github/Aathavan05/DataScience-Notebooks/blob/main/27Jan2026_DataScience.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

AATHAVAN MANIMARAN [RA2311042010041]

1)Create a Numpy array with Example
2)N dimensional in numpy with an example
3)To generate a range of value from 12 to 15 with step value is 3
4)Explain the Shape of 2d array and the size with example
5)reshape the value of [15 to 30]

### 1) Create a Numpy array with Example

In [ ]:
import numpy as np

# Creating a simple 1D NumPy array
array_1d = np.array([10, 20, 30, 40, 50])
print("1D NumPy Array:", array_1d)
print("Type of array:", type(array_1d))

1D NumPy Array: [10 20 30 40 50]
Type of array: <class 'numpy.ndarray'>


### 2) N dimensional in numpy with an example

In [ ]:
import numpy as np

# Creating a 2D (N-dimensional) NumPy array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D NumPy Array:\n", array_2d)
print("Number of dimensions (ndim):", array_2d.ndim)

# Creating a 3D (N-dimensional) NumPy array
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\n3D NumPy Array:\n", array_3d)
print("Number of dimensions (ndim):", array_3d.ndim)

2D NumPy Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Number of dimensions (ndim): 2

3D NumPy Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Number of dimensions (ndim): 3


### 3) To generate a range of value from 12 to 15 with step value is 3

In [ ]:
import numpy as np

# Using np.arange(start, stop, step)
# The 'stop' value is exclusive, so to include 15, we set stop to 16.
range_values = np.arange(12, 16, 3)
print("Generated range from 12 to 15 with step 3:", range_values)

Generated range from 12 to 15 with step 3: [12 15]


### 4) Explain the Shape of 2d array and the size with example

In [ ]:
import numpy as np

# Create a 2D array for demonstration
demo_array_2d = np.array([[10, 11, 12, 13],
                          [14, 15, 16, 17],
                          [18, 19, 20, 21]])

print("Demo 2D Array:\n", demo_array_2d)

# Shape: The 'shape' attribute returns a tuple indicating the dimensions of the array.
# For a 2D array, it will be (number_of_rows, number_of_columns).
print("\nShape of the array (rows, columns):", demo_array_2d.shape)

# Size: The 'size' attribute returns the total number of elements in the array.
# It is the product of the dimensions (e.g., rows * columns for a 2D array).
print("Size of the array (total elements):", demo_array_2d.size)

Demo 2D Array:
 [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]

Shape of the array (rows, columns): (3, 4)
Size of the array (total elements): 12


### 5) reshape the value of [15 to 30]

In [ ]:
import numpy as np

# First, create a 1D array containing values from 15 to 30 (inclusive).
# np.arange(start, stop) generates values up to (but not including) 'stop'.
values_to_reshape = np.arange(15, 31) # This will create [15, 16, ..., 30]
print("Original 1D array:", values_to_reshape)
print("Original shape:", values_to_reshape.shape)
print("Total elements:", values_to_reshape.size)

# To reshape, the new array must have the same number of elements as the original.
# The original array has 16 elements (30 - 15 + 1).
# We can reshape it into a 4x4 array, for example.

# Reshaping into a 4x4 2D array
reshaped_4x4 = values_to_reshape.reshape(4, 4)
print("\nReshaped 4x4 array:\n", reshaped_4x4)
print("Reshaped shape:", reshaped_4x4.shape)

# Another example: Reshaping into a 2x8 2D array
reshaped_2x8 = values_to_reshape.reshape(2, 8)
print("\nReshaped 2x8 array:\n", reshaped_2x8)
print("Reshaped shape:", reshaped_2x8.shape)

# You can also use -1 to automatically calculate one dimension
reshaped_auto_rows = values_to_reshape.reshape(-1, 8) # Auto-calculate rows to make 8 columns
print("\nReshaped (auto rows) x 8 array:\n", reshaped_auto_rows)
print("Reshaped shape:", reshaped_auto_rows.shape)

Original 1D array: [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]
Original shape: (16,)
Total elements: 16

Reshaped 4x4 array:
 [[15 16 17 18]
 [19 20 21 22]
 [23 24 25 26]
 [27 28 29 30]]
Reshaped shape: (4, 4)

Reshaped 2x8 array:
 [[15 16 17 18 19 20 21 22]
 [23 24 25 26 27 28 29 30]]
Reshaped shape: (2, 8)

Reshaped (auto rows) x 8 array:
 [[15 16 17 18 19 20 21 22]
 [23 24 25 26 27 28 29 30]]
Reshaped shape: (2, 8)


Diffrence Between np.empty() and np.zero(),np.full()

### Understanding `np.empty()`, `np.zeros()`, and `np.full()`

These three NumPy functions are fundamental for creating new arrays with a specified shape. The main distinction among them lies in how they initialize the values within the array:

*   **`np.zeros(shape, dtype)`**: This function creates a new array of the given `shape` (e.g., `(2, 3)` for a 2x3 matrix) and `dtype` (data type, e.g., `int`, `float`). All elements in the array are initialized to `0` (zero). This is extremely useful when you need an array where all starting values are known to be zero, often used for accumulating results or as a base for calculations.

*   **`np.empty(shape, dtype)`**: Similar to `np.zeros()` in creating an array of a specified `shape` and `dtype`, but the key difference is that its elements are **not initialized**. This means the array will contain whatever garbage values are present in the memory location allocated for it at that moment. Because it doesn't spend time setting values, `np.empty()` is generally the fastest way to create an array. However, you should only use it if you are immediately going to fill or overwrite all of its elements, as relying on uninitialized values can lead to unpredictable behavior.

*   **`np.full(shape, fill_value, dtype)`**: This function is designed to create an array where all elements are initialized to a specific `fill_value` that you provide. Like the others, it takes a `shape` and `dtype`. It's a versatile choice when you need an array uniformly filled with any constant value other than just zero (which `np.zeros()` handles) or random uninitialized values (which `np.empty()` produces).

In [ ]:
import numpy as np

# Example 1: np.zeros()
# Creates a 2x3 array where all elements are 0.
print("1. np.zeros((2, 3), dtype=int) - Array filled with zeros:")
print(np.zeros((2, 3), dtype=int))
print("\n" + "-"*50 + "\n")

# Example 2: np.empty()
# Creates a 2x3 array with uninitialized (random) values.
# The output will vary each time you run it.
print("2. np.empty((2, 3), dtype=int) - Array with uninitialized (random) values:")
print(np.empty((2, 3), dtype=int))
print("\n" + "-"*50 + "\n")

# Example 3: np.full()
# Creates a 2x3 array where all elements are initialized to 7.
print("3. np.full((2, 3), 7, dtype=int) - Array filled with a specific value (7):")
print(np.full((2, 3), 7, dtype=int))
print("\n" + "-"*50 + "\n")

1. np.zeros((2, 3), dtype=int) - Array filled with zeros:
[[0 0 0]
 [0 0 0]]

--------------------------------------------------

2. np.empty((2, 3), dtype=int) - Array with uninitialized (random) values:
[[0 0 0]
 [0 0 0]]

--------------------------------------------------

3. np.full((2, 3), 7, dtype=int) - Array filled with a specific value (7):
[[7 7 7]
 [7 7 7]]

--------------------------------------------------



np.eye() and np.identity()

### Understanding `np.eye()` and `np.identity()`

Both `np.eye()` and `np.identity()` are used to create identity matrices, which are square matrices where all the main diagonal elements are 1 and all other elements are 0. However, they have slightly different use cases and flexibility:

*   **`np.identity(n, dtype=None)`**:
    *   Creates a square identity matrix of size `n x n`. This means it will always have the same number of rows and columns.
    *   It's a specialized function specifically for square identity matrices.
    *   The primary argument is `n`, which defines both the number of rows and columns.

*   **`np.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')`**:
    *   Creates a 2-D array (matrix) with ones on the `k`-th diagonal and zeros elsewhere.
    *   `N` is the number of rows.
    *   `M` (optional) is the number of columns. If not provided, `M` defaults to `N`, making it a square matrix.
    *   `k` (optional) is the index of the diagonal. `k=0` (default) refers to the main diagonal, `k>0` refers to diagonals above the main diagonal, and `k<0` refers to diagonals below the main diagonal.
    *   `np.eye()` is more general than `np.identity()` because it allows you to create non-square matrices and place ones on off-diagonals.

In [ ]:
import numpy as np

# Example 1: np.identity()
# Creates a 3x3 identity matrix
print("1. np.identity(3) - 3x3 Identity Matrix:")
print(np.identity(3))
print("\n" + "-"*50 + "\n")

# Example 2: np.eye() - default (main diagonal)
# Creates a 3x3 identity matrix (similar to np.identity(3))
print("2. np.eye(3) - 3x3 Identity Matrix (main diagonal, k=0):")
print(np.eye(3))
print("\n" + "-"*50 + "\n")

# Example 3: np.eye() - non-square matrix
# Creates a 3x4 matrix with ones on the main diagonal
print("3. np.eye(3, M=4) - 3x4 matrix with ones on main diagonal:")
print(np.eye(3, M=4))
print("\n" + "-"*50 + "\n")

# Example 4: np.eye() - off-diagonal (k=1)
# Creates a 3x3 matrix with ones on the first super-diagonal
print("4. np.eye(3, k=1) - 3x3 matrix with ones on super-diagonal (k=1):")
print(np.eye(3, k=1))
print("\n" + "-"*50 + "\n")

# Example 5: np.eye() - off-diagonal (k=-1)
# Creates a 3x3 matrix with ones on the first sub-diagonal
print("5. np.eye(3, k=-1) - 3x3 matrix with ones on sub-diagonal (k=-1):")
print(np.eye(3, k=-1))
print("\n" + "-"*50 + "\n")

1. np.identity(3) - 3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

--------------------------------------------------

2. np.eye(3) - 3x3 Identity Matrix (main diagonal, k=0):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

--------------------------------------------------

3. np.eye(3, M=4) - 3x4 matrix with ones on main diagonal:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]

--------------------------------------------------

4. np.eye(3, k=1) - 3x3 matrix with ones on super-diagonal (k=1):
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]

--------------------------------------------------

5. np.eye(3, k=-1) - 3x3 matrix with ones on sub-diagonal (k=-1):
[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]

--------------------------------------------------

